version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    networks:
      - simple-site

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
    networks:
      - simple-site

networks:
  simple-site:
    driver: bridge
