services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - simple-site-network
    environment:
      - CORS_PORT=${CORS_PORT:-3050}
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}

  frontend:
    build: ./frontend
    ports:
      - "3050:80"
    networks:
      - simple-site-network
    environment:
      - VITE_API_URL=${VITE_API_URL:-/api}
      - VITE_REALM=${VITE_REALM:-default-realm}

networks:
  simple-site-network:
    driver: bridge
