services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - simple-site-network
    environment:
      - CORS_PORT=3050

  frontend:
    build: ./frontend
    ports:
      - "3050:80"
    networks:
      - simple-site-network

networks:
  simple-site-network:
    driver: bridge
