services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    networks:
      - simple-site-network
    environment:
      - CORS_PORT=3050
      - DB_HOST=localhost
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=password

  frontend:
    build: ./frontend
    ports:
      - "3050:80"
    networks:
      - simple-site-network
    environment:
      - VITE_API_URL=/api

networks:
  simple-site-network:
    driver: bridge
