version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3005:3005"
    networks:
      - simple-site-network
    environment:
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3050} # Or cheat with '*' to allow all origins
      - DB_HOST=${DB_HOST:-localhost}
      - DB_PORT=${DB_PORT:-3306}
      - DB_USER=${DB_USER:-user}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - JWT_SECRET=${JWT_SECRET:-your_jwt_secret_key}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:3005/api} # This would be your domain if using one like api.yourdomain.com
        VITE_REALM: ${VITE_REALM:-default-realm}
    ports:
      - "3050:3000"
    networks:
      - simple-site-network

networks:
  simple-site-network:
    driver: bridge
